### ISSUE TITLE
Line 42 path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by Boston-of-Gilead** [mailchannels/palinurus#2]
```
line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by fiirhok** [comment]
Can you provide any more information? How did you run palinurus? Especially, what was the value of the `--source` argument?

**Comment by Boston-of-Gilead** [comment]
Hi

Editing for resolution. 
`python.exe .\palinurus.py --source .\templates` was able to resolve this error. 
Thanks :)
